/- -----------------------------------------------------------------
   Programmer(s): Yifan Hu @ UMBC
   -----------------------------------------------------------------
   SUNDIALS Copyright Start
   Copyright (c) 2025-2026, Lawrence Livermore National Security,
   University of Maryland Baltimore County, and the SUNDIALS contributors.
   Copyright (c) 2013-2025, Lawrence Livermore National Security
   and Southern Methodist University.
   Copyright (c) 2002-2013, Lawrence Livermore National Security.
   All rights reserved.

   See the top-level LICENSE and NOTICE files for details.

   SPDX-License-Identifier: BSD-3-Clause
   SUNDIALS Copyright End
   ----------------------------------------------------------------- -/

import FirkodeCert.Basic

/-!
# Data generated from the FIRKODE C sources

GENERATED by `verification/lean/gen_firkode_tables.py`. Do not edit;
rerun the generator instead.
-/

namespace Firkode.Generated

open Q6

/-- `FIRK_MAX_STAGES` (include/firkode/firkode_tables.h) -/
def maxStages : Nat := 9

/-- `FIRK_MAX_CHECK_ORDER` (src/firkode/firkode_tables.c) -/
def maxCheckOrder : Nat := 19

/-- `FIRK_NODE_GRID_PER_STAGE` (src/firkode/firkode_tables.c) -/
def nodeGridPerStage : Nat := 40

/-- `FIRK_DEFAULT_STAGES` (src/firkode/firkode_impl.h) -/
def defaultStages : Nat := 3

/-- Nodes `c` of `firk_radau_closed_form` for `s` = 1, 2, 3 stages. -/
def closedFormC : Nat → List Q6
  | 1 => [1]
  | 2 => [1 / 3, 1]
  | 3 => [(4 - r6) / 10, (4 + r6) / 10, 1]
  | _ => []

/-- Coefficients `A` (row major) of `firk_radau_closed_form`. -/
def closedFormA : Nat → List (List Q6)
  | 1 => [[1]]
  | 2 => [[5 / 12, -1 / 12],
          [3 / 4, 1 / 4]]
  | 3 => [[(88 - 7 * r6) / 360, (296 - 169 * r6) / 1800, (-2 + 3 * r6) / 225],
          [(296 + 169 * r6) / 1800, (88 + 7 * r6) / 360, (-2 - 3 * r6) / 225],
          [(16 - r6) / 36, (16 + r6) / 36, 1 / 9]]
  | _ => []

/-- `firk_gamma0[s]` for s = 0, …, FIRK_MAX_STAGES, as exact decimals. -/
def gamma0Literal : List Rat :=
  [0,
   1,
   0.5,
   0.2748888295956773677478286,
   0.208890675278273738551678,
   0.1590658444274691204779152,
   0.1334999853021741882617498,
   0.1118964653000350759359053,
   0.09833377347648450252097062,
   0.08630100242868910058599241]

/-- Number of digits printed after the decimal point in `firk_gamma0[s]`. -/
def gamma0Digits : List Nat :=
  [0, 0, 1, 25, 24, 25, 25, 25, 26, 26]

/-- SHA-256 of the comment-stripped, whitespace-normalized C definitions
    transcribed by hand in the Lean files. -/
def mirroredFingerprints : List (String × String × String) :=
  [("src/firkode/firkode_tables.c", "firk_radau_poly",
    "d49d712dd2a980921e536d54e13d4822d86165f47ce3baaa46ac168d489ea5e5"),
   ("src/firkode/firkode_tables.c", "firk_radau_nodes",
    "1d914cd72efea190b0ef0de09ad0fa238e7fdecc4199a089fbaf01b3c9fd3219"),
   ("src/firkode/firkode_tables.c", "firk_lagrange_coeffs",
    "f60d8bc32310f4b17ea10d15f8e1904312cb487d48af711e99fb592b1e8e6fec"),
   ("src/firkode/firkode_tables.c", "firk_collocation_coeffs",
    "d1562ef521b394d2b24bcffff9dc8a73a96d09000a4680bfc966c7a57b18198f"),
   ("src/firkode/firkode_tables.c", "firk_derive_ld",
    "65d9d0ec5afc068382afe5eccab7c85bbb190e974fe5284dd5db40ab1743aae9"),
   ("src/firkode/firkode_tables.c", "firk_radau_build",
    "438b5922a597845a8e29ba9f31a2884f69ef46fa1ea57dfa37f04bb9724a4772"),
   ("src/firkode/firkode_tables.c", "FIRKodeTable_CheckOrder",
    "f3b6aae00b8ec8f78a84c51e317af9e0e4a7a29e6014d1f3447e929c7779299e"),
   ("src/firkode/firkode.c", "FIRKodeGetDky",
    "db7291ca2408d667eaf8f5acd80c1cd99ac369df27240b581038be86f9b4e8b6"),
   ("src/firkode/firkode.c", "firkPredict",
    "960a075484e91af408bf4a1355c94f3e17ede39b28c09d3399090f3fc467175a"),
   ("src/firkode/firkode.c", "firkErrorEstimate",
    "e45a00836e20de82ddd2a37f17a42e7c2277052e8caa6533b10824faec6de5ff"),
   ("src/firkode/firkode_io.c", "FIRKodeSetOrder",
    "27071b33861e601b0bbcabc54b1c61e235ba9254929fb372c4de0bedd0735c94")]

end Firkode.Generated
